In [1]:
import tensorflow as tf

In [23]:
t1 = [[1,2,3],[4,5,6]]
t2 = [[7,8,9],[10,11,12]]
tf.concat([t1,t2],axis=0) #在哪个维度上，那个维度值就改变,此处由２行三列改为了四行三列。

<tf.Tensor 'concat_4:0' shape=(4, 3) dtype=int32>

In [14]:
t3 = [[1,2,3],[4,5,6 ]]  #shape[2,3] 
tf.expand_dims(t3,axis=0)  #增加维度

<tf.Tensor 'ExpandDims:0' shape=(1, 2, 3) dtype=int32>

In [5]:
import tensorflow as tf
t3 = [[1,2,3],[4,5,6 ]]
t4 = tf.expand_dims(t3,axis=0)
print(t4)

Tensor("ExpandDims:0", shape=(1, 2, 3), dtype=int32)


In [18]:
import tensorflow as tf
t3 = [[1,2,3],[4,5,6 ]]
t4 = tf.expand_dims(t3,axis=0)
t5 = tf.squeeze(t4)
print(t5)

Tensor("Squeeze_12:0", shape=(2, 3), dtype=int32)


In [19]:
x = tf.constant([1.8,2.2],dtype=tf.float32)
tf.dtypes.cast(x,tf.int32)

<tf.Tensor 'Cast:0' shape=(2,) dtype=int32>

In [21]:
import tensorflow as tf

a = tf.constant([[1,2,3],[4,5,6]])
b = tf.constant([[7,8,9],[10,11,12]])
c1 = tf.concat([a,b],axis=0)
s1 = tf.stack([a,b], axis=0)
c2 = tf.concat([a,b],axis=1)
s2 = tf.stack([a,b], axis=1)
sess = tf.Session()
sess.run(tf.global_variables_initializer())
print(sess.run(c1))
print("\n")
print(sess.run(c2))
print("\n")
print(sess.run(s1))
print("\n")
print(sess.run(s2))


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
